# Generated by Django 5.0.4 on 2024-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('goals_pro', models.IntegerField(default=0)),
                ('goals_con', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
            ],
        ),
    ]
