# Generated by Django 5.0.4 on 2024-05-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_game_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_goals',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_goals',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
