# Generated by Django 5.0.4 on 2024-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_game_away_goals_alter_game_home_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sg',
            field=models.IntegerField(default=0),
        ),
    ]
