# Generated by Django 5.0.4 on 2024-05-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_team_id_name_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
