# Generated by Django 5.0.4 on 2024-05-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_team_logo_team_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_logo',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='game',
            name='home_logo',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
