# Generated by Django 5.0.4 on 2024-05-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_game_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timestamp',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
