# Generated by Django 5.0.4 on 2024-05-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_game_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
