# Generated by Django 5.0.4 on 2024-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_team_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='real_played',
            field=models.BooleanField(default=False),
        ),
    ]
