# Generated by Django 5.0.4 on 2024-05-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_game_real_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='aproveitamento',
            field=models.FloatField(default=0),
        ),
    ]
