# Generated by Django 5.0.4 on 2024-05-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_game_away_logo_remove_game_home_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='local_time',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
