# Generated by Django 5.0.4 on 2024-05-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_game_local_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='league_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='league_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
