# Generated by Django 5.0.4 on 2024-05-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_game_league_id_team_league_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField(blank=True, default=None, null=True)),
                ('league_name', models.CharField(default=None, max_length=30)),
                ('logo', models.CharField(default=None, max_length=150)),
                ('country', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
