# Generated by Django 5.0.4 on 2024-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='url',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
