# Generated by Django 5.0.4 on 2024-05-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_league_zone_1_league_zone_1_txt_league_zone_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='played',
            new_name='simulated',
        ),
    ]
