# Generated by Django 5.0.4 on 2024-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_played_game_simulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stadium',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
