# Generated by Django 5.0.4 on 2024-05-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_game_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='zone_3_txt',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='zone_5_txt',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='zone_reb_txt',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
