# Generated by Django 5.0.4 on 2024-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_league_zone_2_txt_alter_league_zone_4_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
